Ported to TypeScript
MoF-Dev/mofbot pull request #5
Opened 2018-10-28 18:12 UTC by kolatat

- as of #3

2018-10-28 18:14 UTC, kolatat commented
Need you to test cuz I dont have token

2018-10-29 08:13 UTC, aa-tan commented
can I just `node bot.ts` or do I need compilation tool

2018-10-29 08:26 UTC, kolatat commented
You will need to compile (see package.json postinstall script) `npm run postinstall` === `tsc --project .`. The tsc compilation tool will already be installed as it is a dependency (typescript).

When in doubt, `npm install` which will both install dependencies and do the postinstall compilation.

You can also make your IDE/Editor watch changes to \*.ts files and autocompile them into \*.js. Autocompilation is already enabled in IntelliJ settings, and VSCode should have native support? or just have to enable it first.

2018-11-06 02:23 UTC, aa-tan requested changes
Make those changes and I think it'll be good to merge. Also, this suggested change beta thing is pree cool

2018-11-06 02:23 UTC, aa-tan commented on .gitignore
> +**/*.js.map
```suggestion
**/*.js.map

# Project Build location
build/
```
Add build location for compiled JS?

2018-11-06 02:23 UTC, aa-tan commented on package.json
> +    "postinstall": "tsc --project .",
```suggestion
    "postinstall": "tsc --project . --outdir ./build",
```

Add a build directory to make things clean

2018-11-06 12:55 UTC, merged